# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(624, 540))
        MainWindow.setMaximumSize(QtCore.QSize(800, 540))
        MainWindow.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(0,0,0);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setAccessibleName("")
        self.tab.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.tab.setObjectName("tab")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 370, 113, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 430, 111, 24))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label_27.setObjectName("label_27")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 400, 111, 24))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_12.setCheckable(False)
        self.pushButton_12.setChecked(False)
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 460, 111, 24))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.tableWidget_fcfs = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_fcfs.setGeometry(QtCore.QRect(10, 10, 775, 321))
        self.tableWidget_fcfs.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(237,238,240,150);")
        self.tableWidget_fcfs.setObjectName("tableWidget_fcfs")
        self.tableWidget_fcfs.setColumnCount(0)
        self.tableWidget_fcfs.setRowCount(0)
        self.label_fcfs_all = QtWidgets.QLabel(self.tab)
        self.label_fcfs_all.setGeometry(QtCore.QRect(170, 410, 60, 16))
        self.label_fcfs_all.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_fcfs_all.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fcfs_all.setObjectName("label_fcfs_all")
        self.label_fcfs_wait = QtWidgets.QLabel(self.tab)
        self.label_fcfs_wait.setGeometry(QtCore.QRect(170, 370, 61, 16))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_fcfs_wait.setFont(font)
        self.label_fcfs_wait.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_fcfs_wait.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_fcfs_wait.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_fcfs_wait.setScaledContents(False)
        self.label_fcfs_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fcfs_wait.setObjectName("label_fcfs_wait")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(170, 350, 161, 16))
        self.label_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(170, 390, 171, 16))
        self.label_28.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.tab_2.setObjectName("tab_2")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(170, 470, 171, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 370, 113, 21))
        self.lineEdit_5.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 430, 111, 24))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_rr_t = QtWidgets.QLabel(self.tab_2)
        self.label_rr_t.setGeometry(QtCore.QRect(170, 370, 61, 16))
        self.label_rr_t.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_t.setObjectName("label_rr_t")
        self.label_rr_m = QtWidgets.QLabel(self.tab_2)
        self.label_rr_m.setGeometry(QtCore.QRect(170, 410, 61, 16))
        self.label_rr_m.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_m.setObjectName("label_rr_m")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label_22.setObjectName("label_22")
        self.label_rr_p = QtWidgets.QLabel(self.tab_2)
        self.label_rr_p.setGeometry(QtCore.QRect(170, 490, 61, 16))
        self.label_rr_p.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_p.setObjectName("label_rr_p")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(170, 390, 171, 16))
        self.label_23.setObjectName("label_23")
        self.label_rr_r = QtWidgets.QLabel(self.tab_2)
        self.label_rr_r.setGeometry(QtCore.QRect(170, 450, 61, 16))
        self.label_rr_r.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_r.setObjectName("label_rr_r")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(170, 430, 171, 16))
        self.label_24.setObjectName("label_24")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 400, 111, 24))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(170, 350, 201, 16))
        self.label_25.setObjectName("label_25")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 460, 111, 24))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.tableWidget_rr = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_rr.setGeometry(QtCore.QRect(10, 10, 775, 321))
        self.tableWidget_rr.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(237,238,240,150);")
        self.tableWidget_rr.setObjectName("tableWidget_rr")
        self.tableWidget_rr.setColumnCount(0)
        self.tableWidget_rr.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.tab_3.setObjectName("tab_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(170, 470, 171, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 370, 113, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 430, 111, 24))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_sjf_t = QtWidgets.QLabel(self.tab_3)
        self.label_sjf_t.setGeometry(QtCore.QRect(170, 370, 61, 16))
        self.label_sjf_t.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_sjf_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sjf_t.setObjectName("label_sjf_t")
        self.label_sjf_m = QtWidgets.QLabel(self.tab_3)
        self.label_sjf_m.setGeometry(QtCore.QRect(170, 410, 61, 16))
        self.label_sjf_m.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_sjf_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sjf_m.setObjectName("label_sjf_m")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label_17.setObjectName("label_17")
        self.label_sjf_p = QtWidgets.QLabel(self.tab_3)
        self.label_sjf_p.setGeometry(QtCore.QRect(170, 490, 61, 16))
        self.label_sjf_p.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_sjf_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sjf_p.setObjectName("label_sjf_p")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(170, 390, 171, 16))
        self.label_18.setObjectName("label_18")
        self.label_sjf_r = QtWidgets.QLabel(self.tab_3)
        self.label_sjf_r.setGeometry(QtCore.QRect(170, 450, 61, 16))
        self.label_sjf_r.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_sjf_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sjf_r.setObjectName("label_sjf_r")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(170, 430, 171, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 400, 111, 24))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(170, 350, 191, 16))
        self.label_20.setObjectName("label_20")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 460, 111, 24))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableWidget_sjf = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_sjf.setGeometry(QtCore.QRect(10, 10, 775, 321))
        self.tableWidget_sjf.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(237,238,240,150);")
        self.tableWidget_sjf.setObjectName("tableWidget_sjf")
        self.tableWidget_sjf.setColumnCount(0)
        self.tableWidget_sjf.setRowCount(0)
        self.tableWidget_sjf.raise_()
        self.pushButton_15.raise_()
        self.label_sjf_t.raise_()
        self.lineEdit_4.raise_()
        self.pushButton_8.raise_()
        self.label_sjf_r.raise_()
        self.label_18.raise_()
        self.label_sjf_m.raise_()
        self.label_16.raise_()
        self.pushButton_7.raise_()
        self.label_17.raise_()
        self.label_sjf_p.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.tab_4.setObjectName("tab_4")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(170, 470, 171, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 370, 113, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 430, 111, 24))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_psjf_psjf_t = QtWidgets.QLabel(self.tab_4)
        self.label_psjf_psjf_t.setGeometry(QtCore.QRect(170, 370, 61, 16))
        self.label_psjf_psjf_t.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_psjf_psjf_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_psjf_psjf_t.setObjectName("label_psjf_psjf_t")
        self.label_psjf_psjf_m = QtWidgets.QLabel(self.tab_4)
        self.label_psjf_psjf_m.setGeometry(QtCore.QRect(170, 410, 61, 16))
        self.label_psjf_psjf_m.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_psjf_psjf_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_psjf_psjf_m.setObjectName("label_psjf_psjf_m")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label_12.setObjectName("label_12")
        self.label_psjf_psjf_p = QtWidgets.QLabel(self.tab_4)
        self.label_psjf_psjf_p.setGeometry(QtCore.QRect(170, 490, 61, 16))
        self.label_psjf_psjf_p.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_psjf_psjf_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_psjf_psjf_p.setObjectName("label_psjf_psjf_p")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(170, 390, 171, 16))
        self.label_13.setObjectName("label_13")
        self.label_psjf_psjf_m_2 = QtWidgets.QLabel(self.tab_4)
        self.label_psjf_psjf_m_2.setGeometry(QtCore.QRect(170, 450, 61, 16))
        self.label_psjf_psjf_m_2.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_psjf_psjf_m_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_psjf_psjf_m_2.setObjectName("label_psjf_psjf_m_2")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(170, 430, 171, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 400, 111, 24))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(170, 350, 201, 16))
        self.label_15.setObjectName("label_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 460, 111, 24))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.tableWidget_psjf_psjf = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_psjf_psjf.setGeometry(QtCore.QRect(10, 10, 775, 321))
        self.tableWidget_psjf_psjf.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(237,238,240,150);")
        self.tableWidget_psjf_psjf.setObjectName("tableWidget_psjf_psjf")
        self.tableWidget_psjf_psjf.setColumnCount(0)
        self.tableWidget_psjf_psjf.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255,255,255);")
        self.tab_5.setObjectName("tab_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(20, 370, 113, 21))
        self.lineEdit.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(20, 400, 111, 24))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 430, 111, 24))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(170, 350, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_rr_sjf_t = QtWidgets.QLabel(self.tab_5)
        self.label_rr_sjf_t.setGeometry(QtCore.QRect(170, 370, 61, 16))
        self.label_rr_sjf_t.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_sjf_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_sjf_t.setObjectName("label_rr_sjf_t")
        self.label_rr_sjf_m = QtWidgets.QLabel(self.tab_5)
        self.label_rr_sjf_m.setGeometry(QtCore.QRect(170, 410, 61, 16))
        self.label_rr_sjf_m.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_sjf_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_sjf_m.setObjectName("label_rr_sjf_m")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(170, 390, 171, 16))
        self.label_3.setObjectName("label_3")
        self.label_rr_sjf_t_3 = QtWidgets.QLabel(self.tab_5)
        self.label_rr_sjf_t_3.setGeometry(QtCore.QRect(10, 200, 49, 16))
        self.label_rr_sjf_t_3.setText("")
        self.label_rr_sjf_t_3.setObjectName("label_rr_sjf_t_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(170, 430, 171, 16))
        self.label_4.setObjectName("label_4")
        self.label_rr_sjf_r = QtWidgets.QLabel(self.tab_5)
        self.label_rr_sjf_r.setGeometry(QtCore.QRect(170, 450, 61, 16))
        self.label_rr_sjf_r.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_sjf_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_sjf_r.setObjectName("label_rr_sjf_r")
        self.label_rr_sjf_p = QtWidgets.QLabel(self.tab_5)
        self.label_rr_sjf_p.setGeometry(QtCore.QRect(170, 490, 61, 16))
        self.label_rr_sjf_p.setStyleSheet("background-color: rgba(237,238,240,150);")
        self.label_rr_sjf_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rr_sjf_p.setObjectName("label_rr_sjf_p")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(170, 470, 171, 16))
        self.label_5.setObjectName("label_5")
        self.tableWidget_rr_sjf = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_rr_sjf.setGeometry(QtCore.QRect(10, 10, 775, 321))
        self.tableWidget_rr_sjf.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(237,238,240,150);")
        self.tableWidget_rr_sjf.setObjectName("tableWidget_rr_sjf")
        self.tableWidget_rr_sjf.setColumnCount(0)
        self.tableWidget_rr_sjf.setRowCount(0)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 460, 111, 24))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"background-color: rgb(81,129,184);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(69, 111, 158);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Algorithms"))
        self.pushButton_11.setText(_translate("MainWindow", "Сброс"))
        self.label_27.setText(_translate("MainWindow", "Время процесса:"))
        self.pushButton_12.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_14.setText(_translate("MainWindow", "Вычислить"))
        self.label_fcfs_all.setText(_translate("MainWindow", "0"))
        self.label_fcfs_wait.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Среднее время ожидания:"))
        self.label_28.setText(_translate("MainWindow", "Среднее общее время:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "FCFS"))
        self.label_21.setText(_translate("MainWindow", "Штрафное отношение (P):"))
        self.pushButton_9.setText(_translate("MainWindow", "Сброс"))
        self.label_rr_t.setText(_translate("MainWindow", "0"))
        self.label_rr_m.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "Время процесса:"))
        self.label_rr_p.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "Потерянное время (M):"))
        self.label_rr_r.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "Отношение реактивности(R):"))
        self.pushButton_10.setText(_translate("MainWindow", "Добавить"))
        self.label_25.setText(_translate("MainWindow", "Общее время пребывания (T):"))
        self.pushButton_13.setText(_translate("MainWindow", "Вычислить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "RR"))
        self.label_16.setText(_translate("MainWindow", "Штрафное отношение (P):"))
        self.pushButton_7.setText(_translate("MainWindow", "Сброс"))
        self.label_sjf_t.setText(_translate("MainWindow", "0"))
        self.label_sjf_m.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Время процесса:"))
        self.label_sjf_p.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Потерянное время (M):"))
        self.label_sjf_r.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Отношение реактивности(R):"))
        self.pushButton_8.setText(_translate("MainWindow", "Добавить"))
        self.label_20.setText(_translate("MainWindow", "Общее время пребывания (T):"))
        self.pushButton_15.setText(_translate("MainWindow", "Вычислить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "SJF"))
        self.label_11.setText(_translate("MainWindow", "Штрафное отношение (P):"))
        self.pushButton_5.setText(_translate("MainWindow", "Сброс"))
        self.label_psjf_psjf_t.setText(_translate("MainWindow", "0"))
        self.label_psjf_psjf_m.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "Время процесса:"))
        self.label_psjf_psjf_p.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Потерянное время (M):"))
        self.label_psjf_psjf_m_2.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Отношение реактивности(R):"))
        self.pushButton_6.setText(_translate("MainWindow", "Добавить"))
        self.label_15.setText(_translate("MainWindow", "Общее время пребывания (T):"))
        self.pushButton_16.setText(_translate("MainWindow", "Вычислить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "PSJF PSJF"))
        self.label.setText(_translate("MainWindow", "Время процесса:"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Сброс"))
        self.label_2.setText(_translate("MainWindow", "Общее время пребывания (T):"))
        self.label_rr_sjf_t.setText(_translate("MainWindow", "0"))
        self.label_rr_sjf_m.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Потерянное время (M):"))
        self.label_4.setText(_translate("MainWindow", "Отношение реактивности(R):"))
        self.label_rr_sjf_r.setText(_translate("MainWindow", "0"))
        self.label_rr_sjf_p.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Штрафное отношение (P):"))
        self.pushButton_17.setText(_translate("MainWindow", "Вычислить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "RR SJF"))
